---
config:
  theme: mc
---
flowchart TD
    Start([شروع])
    Start --> A{کاربر ثبت‌نام کرده است؟}
    A -- خیر --> B[ثبت‌نام کاربر]
    B --> C[ورود به سیستم]
    A -- بله --> C[ورود به سیستم]
    C --> D[نمایش داشبورد کاربر]
    D --> E[مشاهده فهرست درس‌ها]
    E --> F[انتخاب درس]
    F --> G[مشاهده محتوای درس]
    G --> H[انجام تمرین‌های تعاملی]
    H --> I[ارسال پاسخ‌ها]
    I --> J[تصحیح خودکار پاسخ‌ها]
    J --> K[محاسبه نمره]
    K --> L[تحلیل عملکرد کاربر]
    L --> M[تعیین سطح و مسیر یادگیری]
    M --> N[پیشنهاد درس یا تمرین بعدی]
    N --> O{ادامه یادگیری؟}
    O -- بله --> E
    O -- خیر --> P[خروج از سیستم]
    D --> Q{نیاز به مربی؟}
    Q -- بله --> R[چت متنی با مربی]
    R --> S[ارسال بازخورد مربی]
    S --> D
    Q -- خیر --> D
    R --> T{جلسه صوتی؟}
    T -- بله --> U[رزرو جلسه صوتی]
    U --> V[برگزاری جلسه آنلاین]
    V --> D
    T -- خیر --> D
    Start --> W[ورود مدیر سیستم]
    W --> X[مدیریت درس‌ها و تمرین‌ها]
    X --> Y[مشاهده گزارش عملکرد کاربران]
    Y --> End([پایان])
    P --> End