---
config:
  theme: mc
---
stateDiagram-v2

    [*] --> احراز_هویت

    احراز_هویت --> آماده_یادگیری : ورود موفق
    احراز_هویت --> [*] : خطا / خروج

    آماده_یادگیری --> مطالعه_درس : انتخاب درس
    مطالعه_درس --> انجام_تمرین : شروع تمرین
    انجام_تمرین --> ارزیابی : ارسال پاسخ
    ارزیابی --> بازخورد : تصحیح خودکار
    بازخورد --> تطبیق_سطح : تحلیل عملکرد

    تطبیق_سطح --> آماده_یادگیری : پیشنهاد مسیر جدید
    تطبیق_سطح --> مطالعه_درس : ادامه مسیر

    آماده_یادگیری --> تعامل_با_مربی : درخواست راهنمایی
    تعامل_با_مربی --> آماده_یادگیری : پایان تعامل

    آماده_یادگیری --> خروج
    خروج --> [*]